/**
 * Orium Setup Wizard - Configuration Generators
 * Generates orium.yaml and .env files from user input.
 */

import { writeFileSync } from 'fs';
import { resolve } from 'path';
import * as yaml from 'js-yaml';
import type { OriumConfig, AdapterConfig } from '../core/config-loader';

export interface WizardAnswers {
  useCase: 'personal' | 'enterprise' | 'experiment' | 'skip';
  adapters: Record<string, AdapterConfig>;
  services: {
    image: boolean;
    audio: boolean;
    video: boolean;
    embedding: boolean;
    code: boolean;
    document: boolean;
    multimodal: boolean;
    music: boolean;
    rag: boolean;
    fineTuning: boolean;
  };
  routing: {
    strategy: string;
    failover: boolean;
    maxRetries: number;
  };
  memory: {
    workingCapacity: number;
    shortTermCapacity: number;
    longTermBackend: string;
  };
  skills: string[];
}

export function generateConfig(answers: WizardAnswers): OriumConfig {
  const config: OriumConfig = {
    version: '0.1.0',
    runtime: {
      mode: answers.useCase === 'enterprise' ? 'cloud' : 'hybrid',
      workers: answers.useCase === 'enterprise' ? 8 : 4,
      timeout: 30000,
    },
    adapters: answers.adapters,
    routing: answers.routing,
    tokenPools: {},
    memory: answers.memory,
    tools: {
      mcpEnabled: true,
      allowedTools: ['*'],
    },
    logging: {
      level: 'info',
      format: 'pretty',
    },
  };

  // Generate token pools for adapters with multiple keys
  for (const [name, adapter] of Object.entries(answers.adapters)) {
    if (adapter.apiKey && adapter.apiKey.includes(',')) {
      const keys = adapter.apiKey.split(',').map((k) => k.trim());
      config.tokenPools[name] = {
        strategy: 'round-robin',
        tokens: keys.map((key) => ({ key })),
      };
      // Use first key as primary
      adapter.apiKey = keys[0];
    }
  }

  return config;
}

export function generateYaml(config: OriumConfig): string {
  const doc: any = {
    version: config.version,
    runtime: config.runtime,
    adapters: config.adapters,
    routing: config.routing,
    tokenPools: config.tokenPools,
    memory: config.memory,
    tools: config.tools,
    logging: config.logging,
  };

  return yaml.dump(doc, {
    indent: 2,
    lineWidth: 120,
    noRefs: true,
    sortKeys: false,
  });
}

export function generateEnvFile(answers: WizardAnswers): string {
  const lines: string[] = [
    '# Orium Environment Configuration',
    '# Generated by orium init',
    '',
  ];

  for (const [name, adapter] of Object.entries(answers.adapters)) {
    if (adapter.apiKey) {
      const envKey = name.toUpperCase().replace(/-/g, '_') + '_API_KEY';
      lines.push(`${envKey}=${adapter.apiKey}`);
    }
    if (adapter.baseUrl) {
      const envKey = name.toUpperCase().replace(/-/g, '_') + '_BASE_URL';
      lines.push(`${envKey}=${adapter.baseUrl}`);
    }
  }

  // Add skill API keys
  if (answers.skills.includes('tavily')) {
    lines.push('TAVILY_API_KEY=');
    lines.push('# Get your key at: https://tavily.com');
  }
  if (answers.skills.includes('nobana')) {
    lines.push('NOBANA_API_KEY=');
    lines.push('# Get your key at: https://nobana.io');
  }
  if (answers.skills.includes('eastmoney')) {
    lines.push('EASTMONEY_API_KEY=');
    lines.push('# EastMoney API configuration');
  }

  lines.push('');
  return lines.join('\n');
}

export function writeConfig(config: OriumConfig, cwd: string = process.cwd()): string {
  const yamlContent = generateYaml(config);
  const configPath = resolve(cwd, 'orium.yaml');
  writeFileSync(configPath, yamlContent, 'utf-8');
  return configPath;
}

export function writeEnvFile(content: string, cwd: string = process.cwd()): string {
  const envPath = resolve(cwd, '.env.orium');
  writeFileSync(envPath, content, 'utf-8');
  return envPath;
}

export function generateExampleYaml(): string {
  const example: Partial<OriumConfig> = {
    version: '0.1.0',
    runtime: {
      mode: 'hybrid',
      workers: 4,
      timeout: 30000,
    },
    adapters: {
      openai: {
        enabled: true,
        apiKey: '${OPENAI_API_KEY}',
        models: ['gpt-4o', 'gpt-4o-mini'],
        priority: 1,
      },
      anthropic: {
        enabled: true,
        apiKey: '${ANTHROPIC_API_KEY}',
        models: ['claude-3-5-sonnet-20241022'],
        priority: 2,
      },
      deepseek: {
        enabled: true,
        apiKey: '${DEEPSEEK_API_KEY}',
        models: ['deepseek-chat'],
        priority: 3,
      },
    },
    routing: {
      strategy: 'fastest',
      failover: true,
      maxRetries: 3,
    },
    memory: {
      workingCapacity: 7,
      shortTermCapacity: 100,
      longTermBackend: 'sqlite',
    },
    tools: {
      mcpEnabled: true,
      allowedTools: ['*'],
    },
    logging: {
      level: 'info',
      format: 'pretty',
    },
  };

  return yaml.dump(example, {
    indent: 2,
    lineWidth: 120,
    noRefs: true,
  });
}
